kind: pipeline
name: default

workspace:
  base: /go
  path: kasvith/kache

steps:
- name: test
  image: golang
  commands:
  - go get github.com/magefile/mage
  - mage vendor
  - mage check


- name: publish
  image: plugins/github-release
  commands:
  - go get github.com/magefile/mage
  - mage vendor
  - mage kachecrossbuild
  settings:
    api_key:
      from_secret: GITHUBAPIKEY
    files: build/*
  when:
    event: tag