language: go

before_install:
  - go get github.com/magefile/mage
  - mage vendor

script:
  - mage check

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  fast_finish: true
  include:
  - os: linux
    go: "1.12.x"
    cache:
      directories:
      - $HOME/.cache/go-build
      - $HOME/gopath/pkg/mod

  - os: osx
    go: "1.12.x"
    cache:
      directories:
      - $HOME/Library/Caches/go-build
      - $HOME/gopath/pkg/mod

jobs:
  include:
  - stage: test
  - stage: deploy
    os: linux
    if: tag IS present
    name: "Github Releases"
    script: skip
    before_deploy: "mage kachecrossbuild"
    deploy:
    - provider: releases
      api_key: $GITHUB_API_KEY
      skip_cleanup: true
      draft: true
      file_glob: true
      file:
      - build/*
      on:
        branch: release
        tags: true

branches:
  except:
  - gh-pages


